### ISSUE TITLE
Voix BestOfVox non reconnu

### ISSUE THREAD

**Issue by Seb85** [Spikharpax/Avatar-WebAPI-Client#1]
Bonsoir Stéphane,

Merci pour le partage de ton nouveau client, je viens de l'installer.

Et j'ai un souci..
Impossible de faire fonctionner ma voix BestOfVox, les autres genre "Hortense" fonctionnent bien.

J'ai tenté de la réinstaller, en vain.

Si tu as une idée je prends :)

**Comment by Spikharpax** [comment]
Je n'ai pas ce type de voix donc je n'ai pas pu tester.
Testé avec Virginie, Sébastien et Hortense.

Sinon, questions:
tu es en 32 ou 64 bits ?
Si en 64, tu avais modifié la base de registre pour android et tu as supprimé tes modifs et refais une install après ?

Tu la vois apparaître dans la liste des voix disponibles dans les fonctions vitales ?

**Comment by Seb85** [comment]
Oui j'avais bien supprimé la clé que tu as indiquée dans la doc

Je vois bien la voix dans la liste dans les fonctions vitales :

![image](https://user-images.githubusercontent.com/9149761/64132295-1c67cd80-cdcf-11e9-95d0-7aca10164267.png)

**Comment by Spikharpax** [comment]
Si tu la vois, cx'est que c'est une voix SAPI, ca devrait donc fonctionner.
Je me demande si c'est le "ç" qui fait que tu ne peux pas l'appeler.

ouvres le fichier main.js et tu décommentes le opendevtools à la ligne 39
Ensuite, tu ouvres le fichier listen.js et tu ajoutes une ligne console.log('voix", voice) avant la ligne 45

if (voice == 'Par défaut') voice = null;
console.log('voix", voice);  // ICI !!!!!!!!!!!!
  Avatar.speak(speech, () => {
    stopListen(true);
  }, voice, volume, speed);

tu sauves, tu relances et tu sélectionnes ta voix dans la liste et tu tests pour voir ce qui apparaît dans la console comme nom de voix.

**Comment by Spikharpax** [comment]
tu peux faire un autre test si tu veux
ouvres le fichier speak.js

à la ligne 28
else if (Config.voices.current && Config.voices.current.toLowerCase() != "par défaut")
        options.voice = Config.voices.current;

modifie par:
else if (Config.voices.current && Config.voices.current.toLowerCase() != "par défaut") {
    if (Config.voices.current.toLowerCase().indexOf("best-of-vox damien") == -1)
        options.voice = Config.voices.current;
   else
      options.voice = "best-of-vox damien (français)"
}

sauve, test

**Comment by Spikharpax** [comment]
En fait j'y pense, si tu dis la règle "donnes-moi les voix disponibles", tu fais exactement la même chose que la 1er test que je t'ai fais faire avec le console.log, ca affiche les voix dans la console. j'avais prévu mais je m'en rappelais plus.  

Regarde la règle dans l'onglet voix dans les fonctions vitales... 
Tu ne l'avais pas fait ?

**Comment by Seb85** [comment]
Le rajout de la ligne : console.log('voix", voice); me plante le démarrage :

![image](https://user-images.githubusercontent.com/9149761/64133064-293af000-cdd4-11e9-94ae-3f880e4a861a.png)

Rien ne se passe, il reste figé.

La modif du speak.js n'a pas fonctionné

Je vois bien la voix lorsque je lui demande celles dispos :

![image](https://user-images.githubusercontent.com/9149761/64133165-a23a4780-cdd4-11e9-8e0e-62bffd6400e7.png)


Merci pour ton aide

**Comment by Spikharpax** [comment]
ben oui c'est normal...
console.log('voix", voice)    avec une cote et une double-cote, en js ca ne peux pas fonctionner...
J'ai tapé un peu vite sur mon clavier mais tu doit savoir comment faire un console.log... monte le niveau seb ... :-)

Sinon :
Sélectionne la voix damien dans les fonctions vitales
Ouvre le fichier avatar.config dans un editeur de texte
cherche "current"
tu dois voir quelque chose comme  "current":"best-of-vox damien (fran?ais)"
Tu vois quoi ? dis-moi

**Comment by Seb85** [comment]
désolé il est tard ^^

Dans le current j'ai beau selectionner la voix dans la config et sauvegarder, j'ai toujours ca :
"current":"Par défaut"

Par contre j'ai reussi a faire apparaitre avant :
"active":["best-of-vox damien (fran?ais)"]

![image](https://user-images.githubusercontent.com/9149761/64133617-be8bb380-cdd7-11e9-8f29-73762891ba2c.png)

**Comment by Spikharpax** [comment]
oui, il est tard... ;-D
Il faut enregistrer en bas de la fenêtre... a mon avis, tu ne l'as pas fait...

Le truc c'est que je ne sais pas si tu as bien écrit ce que je t'ai donné dans le speak.js... J'ai un gros doute. Tu as bien écrit "français" avec un "ç" avec une cédille et pas un c normal ? tu es sûr ? Parce que ca devrait fonctionner.

Si c'est bon et là je dois te faire confiance... arf... :-))) donc c'est encore plus bas niveau qu'il faut chuinter ce foutu caractère spécial... tu as toujours des trucs bizarres toi, tu peux pas faire comme tout le monde ? hmmm ? :-)
Il va falloir aller dans le vbs maintenant pour traper ca.
Je te dirais demain comment faire.

**Comment by Seb85** [comment]
Oui j'avais bien enregistré ^^

Rien ne vaut une capture d'écran :
![image](https://user-images.githubusercontent.com/9149761/64133831-51791d80-cdd9-11e9-8068-02b395f87a1c.png)

Sans moi je sais que tu t’ennuierai ;)

**Comment by Spikharpax** [comment]
si tu cliques sur "COURANTE" et que tu enregistres après, tu dois avoir la voix dans le current et pas "par défaut".
Donc je veux un "current" avec le nom de ta voix et test
au pire si tu ne veux pas cliquer sur "enregistrer" parce que tu es un rebelle,
ajoute à la main dans "current" un "best-of-vox damien (fran?ais)"
ca ira plus vite et on sera fixé

**Comment by Seb85** [comment]
Par le bouton enregistré, il ne voulait pas l'inscrire.

J'ai tenté par le fichier, et la miracle ! Ça fonctionne

Je touche plus a rien ^^

Merci d'avoir pris du temps! Au top :)

**Comment by Spikharpax** [comment]
Ok cool,
Normalement, tu devrais pouvoir sélectionner plusieurs voix et changer.
Mais je vais voir ce que je peux faire pour ce pb et je sortirais une version. Coder en dur le nom dans le speak n'est pas bon.

**Comment by Spikharpax** [comment]
Seb,

J'ai fait une petite modif dans le fichier core/chrome/js/properties.js
J'aimerais que tu tests et que tu me fasses un retour.
Si c'est bon, je l’inclurais dans un patch

[Fichiers à copier](https://github.com/Spikharpax/transfert) 

il y a aussi le Avatar.config à remplacer.
Il est neutre donc tu devras refaire ta config lorsque tu lanceras le client.

Et bien sûr, reviens à une version sans la modif du speak.js pour faire le test :-)
Fais-moi un retour, thx

**Comment by Seb85** [comment]
Bonsoir Stéphane,

Je viens de remplacer les deux fichiers et remis le speak a l'origine.

C'est nif, la voix est bien pris en compte par l'interface ;)

Tu peux le déployer a la prochaine maj !
