### ISSUE TITLE
Plugins Jarvis - avatar muet après exécution d'une commande

### ISSUE THREAD

**Issue by Flamouth** [Spikharpax/Avatar-WebAPI-Client#2]
Salut Stéphane, 
Tous d'abord, j'adore ton nouveau client en une seule fenêtre. Tous fonctionne impec avec Windows 10 et les deux voix paul et julie. 

Voila mon problème. J'ai acquis un moniteur tactile pour mon pc central, j'utilise nircmd pour l'éteindre quand j'ai besoin. J'utilise donc le plugin jarvis pour effectuer la requête. Après le passage de commande qui fonctionne, il se met en sourdine, je peux le remettre via le bouton sur le client (inscription : Merci Dave, Oh Mon Dieu ! C'est plein d'étoiles ^^) , Mais rien n'y fait. Je doit redémarrer le client. Pas d'erreur sur le serveur et client.

le js ci-dessous:
var Promise = require('q').Promise;
require('colors');
exports.action = function(data, callback){
		var tblCommand = {
		screenoff: function() {screenoff(data.client);}
			};
		info("Jarvis command:", data.action.command.yellow, "From:", data.client.yellow);
	tblCommand[data.action.command]();
	callback();
}
function  screenoff(client){
		Avatar.runApp("C:\\Client\\app\\jarvis\\screen\\screenoff.cmd", client);
}

Et par la même occasion du coup, comment fonctionne le mute maintenant, j'ai la règle mute dans le plugin jeedom et l'action dans le js. Je modifiais le speech avant.

mute : function() { requestJeedomMute(data.client, Config.modules.Jeedom.clients[room][data.action.value])},

et

function requestJeedomMute (client, value, txt) {
	
	var uri = _JeedomConf.ip + _JeedomConf.pathJeedomApi + '?apikey=' + _JeedomConf.apikey + '&type=scenario&id=' + 44 + '&action=start';
	
	info('uri:', uri.yellow);
	
	request({
		url: uri,
		method: 'POST'
	},
	function(state) {
		if (txt) {
			Avatar.speak(txt, client, function() {
				Avatar.Speech.end(client);
			});
			} else {
			var answer = !state;
			Avatar.Speech.end(client);
			info(answer);
		}
		},
	function (err, response) {
		if (err || response.statusCode != 200) {
			info('Error: Callback request'.red);
			return callback(false);
		}
	});
}

Merci pour ces petites précisions.

**Comment by Spikharpax** [comment]
Bjr Flamouth,

Pour le mute, que tu passes par Jeedom, c'est uniquement pour muter un périphérique... genre je sais pas... disons ta tv si jeedom la pilote.
Mais passer par jeedom pour faire un mute sur le client... euh... non c'est carrément martien ton truc.
Si tu veux faire un mute du client, il suffit de faire dans un plugin, n'importe lequel:
Pour mute si ton client s'appelle 'Salon' (codé en dur)
Avatar.call('generic', {command: 'muteOnOffClient', set : '0', client: 'Salon'});
Pour mute si ton client est data.client  (on ne connait pas le nom du client, il vient avec la commande)
Avatar.call('generic', {command: 'muteOnOffClient', set : '0', client: data.client});

pour unmute:
Avatar.call('generic', {command: 'muteOnOffClient', set : '1', client: 'Salon'});


J'avoue ne pas trop comprendre ta demande sur le fait d'éteindre le tactile.
Ce tactile est le PC ou se trouve le Serveur ou le Client ?

**Comment by Flamouth** [comment]
J'utilise jeedom pour muter mes périphériques comme la tv, la squeezbox si elle est allumé. Il me faut un scénario pour çà, c'est plus simple de gérer. Surtout quand j'allume la tv pour lancer plex et que le client termine la tv est allumé et lui fait un unmute qui pour moi est la même chose qu'un mute (broadlink oblige :-( )

Après ce n'est qu'un exemple pour éteindre l'affichage de l'écran. Je voulais savoir si tu savais pourquoi le client se met en sourdine après le passage de cette règle. Un problème dans le js je pense.

**Comment by Spikharpax** [comment]
ok j'avais mal compris...

Je pense que tu devrais lire la documentation de développement.
Tu as 2 fonctions mute et unmute qui peuvent être utilisées.

Tu devrais aussi chercher la fonction end()
qui remet l'écoute sur le client...  c'est obligatoire sinon le client n'écoute plus.
C'est fait pour éviter d’exécuter plusieurs commandes en même temps... tu imagines de passer 2 ou 3 commandes en même temps?... toutes les réponses qui s’entremêlent ? ... bref. Donc à la fin de la commande, tu lui dis "OK la commande est finie !! tu peux te remettre à écouter" par le end()... ok ? :-)
Soit dit, tu te trompes sur le fait de redémarrer le client dans ton cas (ou tu as oublié le end()...), ce n'est pas nécessaire. Tu devrais essayer de lui demander l'heure après avoir cliqué sur 'ON/OFF/Reset'. Tu verras bien.
Ce bouton fonctionne. Mais seulement si ton plug-in est correctement développé et retourne TOUJOURS un end() pour remettre l'écoute. Dans le cas contraire, il libère juste l'écoute pour une règle.
Sauf pour le mute et le unmute où il ne faut pas faire de end()... parce que ce ne sont pas des commandes "règle" avec un mot-clé déclencheur, ce n'est pas nécessaire de dire au client "la commande est finie !!" puisque c'est avant et après cette commande...

**Comment by Spikharpax** [comment]
Il faut que je te dise aussi que tu t'ai trompé, c'est un pb sur le plug-in Jarvis. pas sur le client Avatar.
Tu as une bibliothèques de plug-ins et sur chacun, tu as un bouton pour aller directement sur son github et poser ton pb au contributeur qui a développé ce plug-in.

**Comment by Flamouth** [comment]
Ou se trouve cette documentation de développement ? Ça répondra à mes questions du coup. Merci en tous cas.

**Comment by Spikharpax** [comment]
Eh bien dans le menu contextuel du node Serveur, dans Aide->Développement
