### ISSUE TITLE
probleme connection client au serveur

### ISSUE THREAD

**Issue by halimgambit** [Spikharpax/Avatar-WebAPI-Client#4]
bonjour stephane avant tout je ne suis pas content de toi de ce silence et peut etre l'abandon d'avatar, j'ai creer un forum pour avatar pour te le passer, apres c'est ton projet et c'est ton choix
j'ai le client qui ne se conneccte pas au serveur, je suis avec les derniers version d'avatar
serveur avatar version: 3.3
client avatar: webapi client/avatar widows client 3.5
j'ai telecharger les certeficat depuis les parametres de google chrome et ausside windows systeme32-drivers-etc-hosts   
# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
127.0.0.1        localhost     avatar.ia.fr
ca ne donne toujours rien, un aide stp? cordialement

**Comment by Spikharpax** [comment]
Halim,
Je crois que tu devrais être plus sympa dans tes posts. Tu oublies que c'est un freeware que je donne, Je ne te dois rien. 
De plus, que tu crées un forum sans le finir, juste pour dire "j'ai créé un forum...", que tu penses une seconde que je vais m'en occuper, que je ne le fasse pas et que tu me le reproches ensuite... ça te regarde.

Ton problème ne vient pas d'Avatar mais de ta méconnaissance de Windows (qui n'est pas Avatar).
je vais te donner un bon conseil sans aucune méchanceté et que tu devrais suivre:
Achète-toi un Google Home ou un Amazon Echo.
Tu auras exactement ce que tu veux: Un assistant domotique fonctionnel et surtout sans avoir besoin d'aucune connaissance informatique. C'est la meilleure aide que je peux te donner.
